workers:
  typescript:
    cmd: ["symfony", "console", "typescript:build", "--watch"]
  # sass:
  #   cmd: ['symfony', 'console', 'sass:build', '--watch']
  tailwind:
    cmd: ["symfony", "console", "tailwind:build", "--watch"]
  asset-mapper-custom:
    cmd: ["./assetmapper-compile.sh"]
